name: Generate Galaga

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Aveek-Saha/GitHub-Profile-Attractor@v2
        with:
          username: Caiortdev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
